### ISSUE TITLE
Unprocessable Entity error when registering a user

### ISSUE THREAD

**Issue by danny-eng** [danny-eng/nutrition-app#1]
When registering a user into an a token auth system via Postman, there is an error that describes the password parameter being "blank".

Input:
```
{
    "username": "Admin",
    "password": "123456",
    "email": "dannyeng94@gmail.com",
    "first_name": "Danny",
    "last_name": "Eng"
}
```
Terminal output:
```
Started POST "/users" for 127.0.0.1 at 2017-12-14 12:29:17 -0500
Processing by UsersController#create as */*
  Parameters: {"username"=>"Admin", "password"=>"[FILTERED]", "email"=>"dannyeng94@gmail.com", "first_name"=>"Danny", "last_name"=>"Eng", "user"=>{"username"=>"Admin", "email"=>"dannyeng94@gmail.com", "first_name"=>"Danny", "last_name"=>"Eng"}}
   (0.4ms)  BEGIN
  User Exists (0.9ms)  SELECT  1 AS one FROM "users" WHERE "users"."username" = $1 LIMIT $2  [["username", "Admin"], ["LIMIT", 1]]
   (0.3ms)  ROLLBACK
Completed 422 Unprocessable Entity in 33ms (ActiveRecord: 1.7ms)


  
ActiveRecord::RecordInvalid (Validation failed: Password can't be blank):
  
app/controllers/users_controller.rb:5:in `create'
```
The `user` hash inside the parameter field missing a password key/value pair is what I think is causing the problem, but I don't know where to go to fix it.

@teikmeout @jlr7245 @dominic-farquharson

**Comment by jlr7245** [comment]
Make sure you have the request formatted like this:

```
{
  "user": {
     [all the stuff]
   }
}
```

Otherwise it wont work in the `user_params` method

see [note after the register submit section](https://git.generalassemb.ly/wdi-nyc-thundercats/Rails-React-Token-Auth/blob/master/README.md#formatting-registration-and-login-requests)

**Comment by danny-eng** [comment]
yay, thanks!
