### ISSUE TITLE
Heroku error: <input type="password"> not working

### ISSUE THREAD

**Issue by danny-eng** [danny-eng/nutrition-app#4]
As it says in the title.

Hosting the files locally shows proper "security" for inputs labeled password.

Heroku hosting fails to secure the passwords of the Login and Register components.

Link to the Heroku repo: https://danny-eng-nutrition-app.herokuapp.com/

**Comment by danny-eng** [comment]
Update: On opening localhost again, the problem persists on the same components. Might be syntax error on my part. I'll look for it.

**Comment by danny-eng** [comment]
Update: Fixed the problem appearing in localhost. Returning to Heroku version.

**Comment by danny-eng** [comment]
Update: Problem fixed.

**Comment by teikmeout** [comment]
careful with dependencies not being in the right places, you are missing axios and react router in client, maybe you haven't pushed in a while. 👍
